"""Initial schema

Revision ID: a9036d98e2a1
Revises:
Create Date: 2026-04-09 17:48:48.826827

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a9036d98e2a1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Clean Slate implementation."""
    # 1. Drop EVERYTHING existing to ensure a clean state as requested
    op.execute("DROP TABLE IF EXISTS predictions CASCADE")
    op.execute("DROP TABLE IF EXISTS model_registry CASCADE")
    op.execute("DROP TABLE IF EXISTS drift_reports CASCADE")
    op.execute("DROP TABLE IF EXISTS raw_rides CASCADE")
    op.execute("DROP TABLE IF EXISTS retrain_runs CASCADE")

    # 2. Create Model Registry Table
    op.create_table(
        "model_registry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("rmse", sa.Float(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("r2", sa.Float(), nullable=True),
        sa.Column(
            "deployed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("n_features", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_registry_id"), "model_registry", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_model_registry_version"), "model_registry", ["version"], unique=True
    )

    # 3. Create Predictions Table
    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "input_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("predicted_fare", sa.Float(), nullable=False),
        sa.Column("price_multiplier", sa.Float(), nullable=True),
        sa.Column("demand_supply_ratio", sa.Float(), nullable=True),
        sa.Column("confidence_lower", sa.Float(), nullable=True),
        sa.Column("confidence_upper", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_predictions_id"), "predictions", ["id"], unique=False)
    op.create_index(
        op.f("ix_predictions_model_version"),
        "predictions",
        ["model_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_predictions_request_id"), "predictions", ["request_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "predictions",
        sa.Column(
            "number_of_past_rides", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "predictions",
        sa.Column(
            "customer_loyalty_status", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "predictions",
        sa.Column("ride_accepted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "predictions",
        sa.Column(
            "time_of_booking",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "predictions",
        sa.Column(
            "average_rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "predictions",
        sa.Column("vehicle_type", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "predictions",
        sa.Column("location_category", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "predictions",
        sa.Column(
            "actual_fare",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "predictions",
        sa.Column("number_of_riders", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "predictions",
        sa.Column(
            "expected_ride_duration",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "predictions",
        sa.Column(
            "number_of_drivers", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_predictions_request_id"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_model_version"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_id"), table_name="predictions")
    op.create_unique_constraint(
        op.f("predictions_request_id_key"),
        "predictions",
        ["request_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_predictions_timestamp"),
        "predictions",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_predictions_model_version"),
        "predictions",
        ["model_version"],
        unique=False,
    )
    op.create_index(
        op.f("idx_predictions_location"),
        "predictions",
        ["location_category"],
        unique=False,
    )
    op.alter_column(
        "predictions",
        "model_version",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "predictions",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "predictions",
        "request_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "predictions",
        "id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.drop_column("predictions", "input_features")
    op.add_column(
        "model_registry",
        sa.Column(
            "mape",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "model_registry",
        sa.Column("artifact_path", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "model_registry",
        sa.Column(
            "training_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "model_registry",
        sa.Column("trained_on_rows", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "model_registry",
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_model_registry_version"), table_name="model_registry")
    op.drop_index(op.f("ix_model_registry_id"), table_name="model_registry")
    op.create_unique_constraint(
        op.f("model_registry_version_key"),
        "model_registry",
        ["version"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "model_registry",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "model_registry",
        "rmse",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "model_registry",
        "model_type",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "model_registry",
        "version",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "model_registry",
        "id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.drop_column("model_registry", "path")
    op.drop_column("model_registry", "n_features")
    op.create_table(
        "retrain_runs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "run_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("triggered_by", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("data_version", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("new_model_version", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "new_rmse",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "production_rmse",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "promoted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("mlflow_run_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["new_model_version"],
            ["model_registry.version"],
            name=op.f("retrain_runs_new_model_version_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("retrain_runs_pkey")),
    )
    op.create_table(
        "raw_rides",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ingested_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("number_of_riders", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "number_of_drivers", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("location_category", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("vehicle_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "customer_loyalty_status", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "number_of_past_rides", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "average_rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "time_of_booking",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expected_ride_duration",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "historical_cost_of_ride",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "source",
            sa.TEXT(),
            server_default=sa.text("'api'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("raw_rides_pkey")),
    )
    op.create_index(
        op.f("idx_raw_rides_ingested_at"),
        "raw_rides",
        [sa.literal_column("ingested_at DESC")],
        unique=False,
    )
    op.create_table(
        "drift_reports",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "report_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("feature_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "psi_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ks_statistic",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ks_p_value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "drift_detected",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("drift_reports_pkey")),
    )
    op.create_index(
        op.f("idx_drift_reports_feature"),
        "drift_reports",
        ["feature_name"],
        unique=False,
    )
    op.create_index(
        op.f("idx_drift_reports_date"),
        "drift_reports",
        [sa.literal_column("report_date DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
